# BEGIN_KITTY_FONTS
font_family      family="Overpass Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size           9.5
background_opacity  0.85
copy_on_select      yes
repaint_delay       8
input_delay         3
enabled_layouts     splits,stack
modify_font         baseline -2 

map ctrl+v         launch --location=vsplit --cwd=current
map ctrl+s         launch --location=hsplit --cwd=current
map ctrl+h         neighboring_window left
map ctrl+l         neighboring_window right
map ctrl+k         neighboring_window up
map ctrl+j         neighboring_window down
map ctrl+left      resize_window narrower 2
map ctrl+right     resize_window wider 2
map ctrl+up        resize_window taller 2
map ctrl+down      resize_window shorter 2
map ctrl+z         toggle_layout stack
map ctrl+w         close_window
map ctrl+t         new_tab_with_cwd
map ctrl+shift+w   close_tab
map ctrl+1         goto_tab 1
map ctrl+2         goto_tab 2
map ctrl+3         goto_tab 3
map ctrl+4         goto_tab 4
map ctrl+5         goto_tab 5
map ctrl+shift+[   previous_tab
map ctrl+shift+]   next_tab
