background {
    monitor =
}

input-field {
    monitor =
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    position = -100, 100
    font_family = Geist Mono
    font_size = 40
    halign = right
    valign = bottom
}
